import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../styles/global.css';
import { MainHeader } from '../components/layout';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App For Event Booking',
  description:
    'This is a demo for Event booking, and it is Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainHeader />
        <main>{children}</main>
      </body>
    </html>
  );
}
